package pl.marbirch.boilapp.ui.roads

object Roads {
    const val startScreen = "startScreen"
    const val quizScreen = "quizScreen"
    const val theoryScreen = "theoryScreen"
    const val openTasksScreen = "openTasksScreen"
    const val cpmMethod = "cpmMethod"
    const val cpmCostMethod = "cpmCostMethod"
    const val doapMethod = "doapMethod"
    const val optRozMethod = "optRozMethod"
    const val zadWielMethod = "ZadWielMethod"
    const val cpmFirstStep = "cpmFirstStep"
    const val cpmSecondStep = "cpmSecondStep"
    const val cpmThirdStep = "cpmThirdStep"
    const val cpmFourthStep = "cpmFourthStep"
    const val cpmFifthStep = "cpmFifthStep"
    const val IncorrectCpmFirstAnswer = "IncorrectCpmFirstAnswer"
    const val IncorrectCpmSecondAnswer = "IncorrectCpmSecondAnswer"
    const val IncorrectCpmThirdAnswer = "IncorrectCpmThirdAnswer"
    const val IncorrectCpmFourthAnswer = "IncorrectCpmFourthAnswer"
    const val IncorrectCpmFifthAnswer = "IncorrectCpmFifthAnswer"
    const val cpmCostFirstStep = "cpmCostFirstStep"
    const val cpmCostSecondStep = "cpmCostSecondStep"
    const val cpmCostThirdStep = "cpmCostThirdStep"
    const val cpmCostFourthStep = "cpmCostFourthStep"
    const val cpmCostFifthStep = "cpmCostFifthStep"
    const val cpmCostSixthStep = "cpmCostSixthStep"
    const val cpmCostSeventhStep = "cpmCostSeventhStep"
    const val IncorrectCpmCostAnswer = "IncorrectCpmCostAnswer"
    const val FinishedOpenTaskScreen = "FinishedOpenTaskScreen"
    const val doapFirstStep = "doapFirstStep"
    const val doapSecondStep = "doapSecondStep"
    const val doapThirdStep = "doapThirdStep"
    const val doapFourthStep = "doapFourthStep"
    const val doapFifthStep = "doapFifthStep"
    const val doapSixthStep = "doapSixthStep"
}